### PR TITLE
remove Python 2.7 support and fix PyGIWarning

### PR DESCRIPTION
**Pull request by nobodywasishere**
This PR removes (EOL) Python 2.7 support, converting all code to Python 3 only. This also fixes a PyGIWarning regarding specifying versions of pycairo and pango, and removes unnecessary blank spaces.

### CODE REVIEW

**Comment by daniellimws** [comment]
@mithro What do you think about this? It looks ok to me but I didn't test the changes. Not sure if the changes to some of the imports may break stuff.

**Comment by mithro** [comment]
Let's proceed!

**Comment by mithro** [comment]
BTW You should request my review.

**Comment by daniellimws** [comment]
Cool, I can do a quick test on this on one of the next few days.

**Comment by mithro** [comment]
@daniellimws Great!

**Review by mithro — APPROVED** [review]

**Pull request merged**
